//! `deck.lock` — the versions a deck was authored against (design doc 20).

use camino::Utf8Path;
use serde::{Deserialize, Serialize};

use crate::config::LOCK_FILE;
use crate::error::{Error, Result, read_to_string, write_file};

/// anime.js version bundled under `/@deck/vendor/`.
pub const ANIMEJS_VERSION: &str = "4.5.0";
/// Tailwind CSS browser build bundled under `/@deck/vendor/`.
pub const TAILWIND_VERSION: &str = "4.3.3";
/// Version of the built-in component set.
pub const COMPONENTS_VERSION: &str = env!("CARGO_PKG_VERSION");
/// Version of the built-in theme.
pub const THEME_VERSION: &str = env!("CARGO_PKG_VERSION");

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Lock {
    #[serde(default = "default_schema")]
    pub schema: u32,
    #[serde(default)]
    pub deck_runtime: String,
    #[serde(default)]
    pub animejs: String,
    #[serde(default)]
    pub tailwindcss: String,
    #[serde(default)]
    pub components: String,
    #[serde(default)]
    pub theme: String,
    /// Chromium build the deck was last checked with.
    #[serde(default, skip_serializing_if = "String::is_empty")]
    pub chromium: String,
}

const fn default_schema() -> u32 {
    1
}

impl Default for Lock {
    fn default() -> Self {
        Self {
            schema: 1,
            deck_runtime: env!("CARGO_PKG_VERSION").to_owned(),
            animejs: ANIMEJS_VERSION.to_owned(),
            tailwindcss: TAILWIND_VERSION.to_owned(),
            components: COMPONENTS_VERSION.to_owned(),
            theme: THEME_VERSION.to_owned(),
            chromium: String::new(),
        }
    }
}

impl Lock {
    pub fn load(root: &Utf8Path) -> Result<Option<Self>> {
        let path = root.join(LOCK_FILE);
        if !path.is_file() {
            return Ok(None);
        }
        let text = read_to_string(&path)?;
        toml::from_str(&text)
            .map(Some)
            .map_err(|error| Error::config(format!("{LOCK_FILE}: {error}")))
    }

    pub fn save(&self, root: &Utf8Path) -> Result<()> {
        let text = toml::to_string_pretty(self)
            .map_err(|error| Error::config(format!("{LOCK_FILE} を書き出せません: {error}")))?;
        write_file(&root.join(LOCK_FILE), format!("# Generated by deck.\n{text}"))
    }

    /// Differences between the lock file and this binary.
    pub fn drift(&self) -> Vec<String> {
        let current = Self::default();
        let mut drift = Vec::new();
        for (name, locked, actual) in [
            ("deck runtime", &self.deck_runtime, &current.deck_runtime),
            ("anime.js", &self.animejs, &current.animejs),
            ("tailwindcss", &self.tailwindcss, &current.tailwindcss),
            ("components", &self.components, &current.components),
            ("theme", &self.theme, &current.theme),
        ] {
            if !locked.is_empty() && locked != actual {
                drift.push(format!("{name}: deck.lock={locked} / 実行中={actual}"));
            }
        }
        drift
    }
}
